CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  phone VARCHAR(50),
  password VARCHAR(255) NOT NULL,
  role VARCHAR(20) DEFAULT 'user',
  status VARCHAR(20) DEFAULT 'pending',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS topics (id SERIAL PRIMARY KEY, name VARCHAR(255), description TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS exams (id SERIAL PRIMARY KEY, topic_id INT REFERENCES topics(id), title VARCHAR(255), description TEXT, time_limit INT DEFAULT 30, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS questions (
  id SERIAL PRIMARY KEY,
  exam_id INT REFERENCES exams(id) ON DELETE CASCADE,
  question_text TEXT NOT NULL,
  question_image VARCHAR(512),
  option_images JSONB,
  options JSONB NOT NULL,
  correct_index INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS attempts (id SERIAL PRIMARY KEY, user_id INT REFERENCES users(id), exam_id INT REFERENCES exams(id), answers JSONB, score INT, total_questions INT, started_at TIMESTAMP, completed_at TIMESTAMP);
